"""Data sources endpoint: lists the demo brand's seed CSVs and serves downloads.

The CSVs are generated by `app.seed.generate_csvs` on demand (idempotent) so the
backend never serves a stale or missing file. The manifest captures the demo
narrative for the Data Sources page in the frontend.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from app.config import settings
from app.seed.generate_csvs import generate_all

router = APIRouter(prefix="/data-sources", tags=["data-sources"])


def _data_dir() -> Path:
    p = Path(settings.data_dir)
    if not p.is_absolute():
        # Resolve relative to project root (backend/crm-api -> ../../data)
        p = (Path(__file__).resolve().parents[3] / p).resolve()
    return p


def _ensure_generated() -> Path:
    d = _data_dir()
    manifest = d / "manifest.json"
    if not manifest.exists():
        generate_all(d)
    return d


@router.get("")
def list_sources() -> dict:
    d = _ensure_generated()
    manifest = json.loads((d / "manifest.json").read_text(encoding="utf-8"))
    return manifest


@router.post("/regenerate")
def regenerate() -> dict:
    d = _data_dir()
    return generate_all(d)


@router.get("/{filename}/preview")
def preview(filename: str, limit: int = 8) -> dict:
    d = _ensure_generated()
    path = d / filename
    if not path.exists() or path.suffix.lower() != ".csv":
        raise HTTPException(status_code=404, detail="file not found")
    rows: list[dict[str, str]] = []
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for i, row in enumerate(reader):
            if i >= limit:
                break
            rows.append(row)
        headers = reader.fieldnames or []
    return {"filename": filename, "headers": headers, "rows": rows, "limit": limit}


@router.get("/{filename}/download")
def download(filename: str) -> FileResponse:
    d = _ensure_generated()
    path = d / filename
    if not path.exists() or path.suffix.lower() != ".csv":
        raise HTTPException(status_code=404, detail="file not found")
    return FileResponse(path, media_type="text/csv", filename=filename)
