"""initial schema

Revision ID: 1b34f22c90d6
Revises: 
Create Date: 2026-06-12 00:58:49.579775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b34f22c90d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('parsed_output', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_event_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_provider_event_id'), ['provider_event_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('master_customer_id', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('primary_phone', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('loyalty_tier', sa.String(length=32), nullable=True),
    sa.Column('lifetime_value', sa.Float(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_master_customer_id'), ['master_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_primary_email'), ['primary_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_primary_phone'), ['primary_phone'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mapping_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_brand_id'), ['brand_id'], unique=False)

    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition_json', sa.JSON(), nullable=False),
    sa.Column('preview_count', sa.Integer(), nullable=False),
    sa.Column('created_by_ai', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_brand_id'), ['brand_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('channel_policy_json', sa.JSON(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('ai_plan_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_targeted', sa.Integer(), nullable=False),
    sa.Column('total_skipped', sa.Integer(), nullable=False),
    sa.Column('ai_insight', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_brand_id'), ['brand_id'], unique=False)

    op.create_table('consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_opted_in', sa.Boolean(), nullable=False),
    sa.Column('sms_opted_in', sa.Boolean(), nullable=False),
    sa.Column('email_opted_in', sa.Boolean(), nullable=False),
    sa.Column('rcs_opted_in', sa.Boolean(), nullable=False),
    sa.Column('dnd_status', sa.Boolean(), nullable=False),
    sa.Column('last_consent_update', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('customer_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=120), nullable=False),
    sa.Column('raw_name', sa.String(length=255), nullable=True),
    sa.Column('raw_phone', sa.String(length=64), nullable=True),
    sa.Column('raw_email', sa.String(length=255), nullable=True),
    sa.Column('normalized_phone', sa.String(length=16), nullable=True),
    sa.Column('normalized_email', sa.String(length=255), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_record_id', name='uq_identity_source')
    )
    with op.batch_alter_table('customer_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_identities_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_identity_norm_email', ['normalized_email'], unique=False)
        batch_op.create_index('ix_identity_norm_phone', ['normalized_phone'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_order_id', sa.String(length=120), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('store_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_system', 'source_order_id', name='uq_order_source')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_order_customer_date', ['customer_id', 'order_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)

    op.create_table('staged_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('normalized', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staged_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staged_records_import_batch_id'), ['import_batch_id'], unique=False)

    op.create_table('communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('resolved_channel', sa.String(length=32), nullable=True),
    sa.Column('routing_reason', sa.String(length=255), nullable=True),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('rendered_message', sa.Text(), nullable=True),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.create_index('ix_comm_campaign_status', ['campaign_id', 'current_status'], unique=False)
        batch_op.create_index('ix_comm_provider_msg', ['provider_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_customer_id'), ['customer_id'], unique=False)

    op.create_table('communication_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=120), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_event_id')
    )
    with op.batch_alter_table('communication_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_events_communication_id'), ['communication_id'], unique=False)
        batch_op.create_index('ix_event_comm_seq', ['communication_id', 'sequence'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communication_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_comm_seq')
        batch_op.drop_index(batch_op.f('ix_communication_events_communication_id'))

    op.drop_table('communication_events')
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communications_customer_id'))
        batch_op.drop_index(batch_op.f('ix_communications_campaign_id'))
        batch_op.drop_index('ix_comm_provider_msg')
        batch_op.drop_index('ix_comm_campaign_status')

    op.drop_table('communications')
    with op.batch_alter_table('staged_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staged_records_import_batch_id'))

    op.drop_table('staged_records')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_brand_id'))
        batch_op.drop_index('ix_order_customer_date')

    op.drop_table('orders')
    with op.batch_alter_table('customer_identities', schema=None) as batch_op:
        batch_op.drop_index('ix_identity_norm_phone')
        batch_op.drop_index('ix_identity_norm_email')
        batch_op.drop_index(batch_op.f('ix_customer_identities_customer_id'))

    op.drop_table('customer_identities')
    op.drop_table('consent')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_brand_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_brand_id'))

    op.drop_table('segments')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_brand_id'))

    op.drop_table('import_batches')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_primary_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_primary_email'))
        batch_op.drop_index(batch_op.f('ix_customers_master_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customers_brand_id'))

    op.drop_table('customers')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_provider_event_id'))

    op.drop_table('webhook_deliveries')
    op.drop_table('brands')
    op.drop_table('ai_runs')
    # ### end Alembic commands ###
