"use client";

import type React from "react";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { PageHeader } from "@/components/PageHeader";
import { Stat } from "@/components/Stat";
import { ChannelBadge } from "@/components/ChannelBadge";
import {
  EMPTY_DEFINITION,
  aiGenerateSegment,
  deleteSegment,
  getSegmentTemplates,
  listSegments,
  previewSegmentDef,
  saveSegment,
  type AISegmentResult,
  type SegmentDefinition,
  type SegmentPreviewResponse,
  type SegmentRow,
  type SegmentTemplate,
} from "@/lib/api";
import { fmtInr, fmtNum, fmtRelative } from "@/lib/format";
import { useToast } from "@/components/Toast";
import { AILoader, AILoaderBlock } from "@/components/AILoader";
import { useAIThinking } from "@/components/AIThinking";

const CITIES = [
  "Bengaluru", "Mumbai", "Delhi", "Pune", "Hyderabad",
  "Chennai", "Kolkata", "Ahmedabad", "Jaipur", "Indore",
  "Chandigarh", "Kochi", "Surat", "Gurugram", "Noida",
];
const TIERS = ["bronze", "silver", "gold", "platinum"];

export default function SegmentsPage() {
  const [definition, setDefinition] = useState<SegmentDefinition>(EMPTY_DEFINITION);
  const [preview, setPreview] = useState<SegmentPreviewResponse | null>(null);
  const [previewing, setPreviewing] = useState(false);

  const [templates, setTemplates] = useState<SegmentTemplate[]>([]);
  const [saved, setSaved] = useState<SegmentRow[]>([]);

  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);

  // AI segment generator
  const [aiPrompt, setAiPrompt] = useState("");
  const [aiResult, setAiResult] = useState<AISegmentResult | null>(null);
  const [aiBusy, setAiBusy] = useState(false);
  const [aiError, setAiError] = useState<string | null>(null);
  const toast = useToast();
  const ai = useAIThinking();

  const onAiGenerate = async () => {
    if (!aiPrompt.trim()) return;
    setAiBusy(true);
    setAiError(null);
    const r = await ai.run("Generating segment with AI…", () => aiGenerateSegment(aiPrompt));
    setAiBusy(false);
    if (!r) {
      setAiError("AI call failed. Check /ai-runs for details.");
      toast.error("AI call failed", "Check /ai-runs for the failed run.");
      return;
    }
    setAiResult(r);
    setDefinition(r.definition);
    toast.success(
      "Segment generated by AI",
      `${r.count} customers match · ${r.provider}/${r.model} · ${r.latency_ms}ms`
    );
    // Suggest a name from the prompt's first few words if blank
    if (!name) setName(aiPrompt.split(/\s+/).slice(0, 6).join(" "));
  };

  const SAMPLE_PROMPTS = [
    "high paying customers who haven't ordered in 30 days",
    "first-time buyers in Bengaluru reachable on WhatsApp",
    "VIP gold and platinum members across all three sources",
    "active customers in the last 14 days with 3 or more orders",
  ];

  useEffect(() => {
    getSegmentTemplates().then(setTemplates);
    listSegments().then(setSaved);
  }, []);

  // Debounced live preview
  useEffect(() => {
    let cancelled = false;
    const t = setTimeout(() => {
      setPreviewing(true);
      previewSegmentDef(definition, 5).then((p) => {
        if (cancelled) return;
        setPreview(p);
        setPreviewing(false);
      });
    }, 250);
    return () => {
      cancelled = true;
      clearTimeout(t);
    };
  }, [definition]);

  const onApplyTemplate = (t: SegmentTemplate) => {
    setDefinition(t.definition);
    setName(t.name);
    setDescription(t.description);
  };

  const onSave = async () => {
    if (!name.trim()) {
      setSaveError("Give the segment a name first.");
      return;
    }
    setSaveError(null);
    setSaving(true);
    const r = await saveSegment({ name, description, definition });
    setSaving(false);
    if (!r) {
      setSaveError("Save failed. Check backend logs.");
      toast.error("Save failed", "Backend rejected the segment. Check logs.");
      return;
    }
    setSaved([r, ...saved]);
    setName("");
    setDescription("");
    toast.success("Segment saved", `${r.name} · ${r.preview_count} customers matched`);
  };

  const onDelete = async (id: number) => {
    if (!confirm("Delete this segment?")) return;
    const ok = await deleteSegment(id);
    if (ok) {
      setSaved(saved.filter((s) => s.id !== id));
      toast.info("Segment deleted");
    } else {
      toast.error("Delete failed");
    }
  };

  const isPristine = useMemo(
    () => JSON.stringify(definition) === JSON.stringify(EMPTY_DEFINITION),
    [definition]
  );

  return (
    <div className="min-h-screen animate-fade-in">
      <PageHeader
        eyebrow="Engagement"
        title="Segments"
        description="Define audiences as auditable JSON. Filters compose with AND. Consent-aware suppression is baked in. Preview the count, who matches, and why — live."
      />

      <div className="px-8 py-8 max-w-7xl space-y-8">
        {/* AI segment generator */}
        <section className="neu-card accent-violet p-5">
          <div className="flex items-start justify-between gap-4 mb-3">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="text-[10px] uppercase tracking-widest text-c-violet font-semibold">
                  AI · segment generator
                </span>
                <span className="text-[10px] uppercase tracking-wider text-[var(--neu-text-subtle)]">
                  validated · audited
                </span>
              </div>
              <p className="text-sm text-[var(--neu-text-muted)] max-w-2xl">
                Describe your audience in plain English. The model returns a structured
                definition, validated against the same Pydantic schema as the manual
                builder. AI proposes; the deterministic engine executes.
              </p>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-2">
            <input
              value={aiPrompt}
              onChange={(e) => setAiPrompt(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !aiBusy) onAiGenerate();
              }}
              placeholder='e.g., "high-paying customers who haven&apos;t ordered in 30 days"'
              className="flex-1 neu-input px-3 py-2 text-sm"
            />
            <button
              onClick={onAiGenerate}
              disabled={aiBusy || !aiPrompt.trim()}
              className="neu-btn neu-btn-primary px-4 py-2 text-sm min-w-[160px]"
            >
              {aiBusy ? <AILoader label="Generating…" /> : "Generate with AI"}
            </button>
          </div>

          <div className="mt-3 flex flex-wrap gap-1.5">
            <span className="text-[11px] text-[var(--neu-text-subtle)] mr-1">Try:</span>
            {SAMPLE_PROMPTS.map((p) => (
              <button
                key={p}
                onClick={() => setAiPrompt(p)}
                className="text-[11px] neu-raised-xs px-2.5 py-1 hover:text-xeno transition"
              >
                {p}
              </button>
            ))}
          </div>

          {aiError && (
            <div className="mt-3 neu-inset-sm px-3 py-2 text-xs text-c-rose">
              {aiError}
            </div>
          )}

          {aiResult && (
            <div className="mt-4 neu-inset-sm p-3">
              <div className="flex items-baseline justify-between gap-2 mb-1">
                <div className="text-[10px] uppercase tracking-wider text-[var(--neu-text-subtle)]">
                  AI rationale
                </div>
                <div className="text-[10px] font-mono text-[var(--neu-text-subtle)]">
                  {aiResult.provider}/{aiResult.model} · {aiResult.latency_ms}ms ·{" "}
                  <span
                    className={
                      aiResult.validation_status === "ok"
                        ? "text-c-emerald"
                        : aiResult.validation_status === "retry_used"
                        ? "text-xeno"
                        : "text-c-amber"
                    }
                  >
                    {aiResult.validation_status}
                  </span>
                </div>
              </div>
              <p className="text-sm text-[var(--neu-text)]">{aiResult.rationale}</p>
              <div className="mt-2 text-xs text-c-violet">
                Definition loaded into the builder below. Tweak, then save.
              </div>
            </div>
          )}
        </section>

        {/* Pre-built templates strip */}
        <section>
          <h2 className="text-[11px] uppercase tracking-widest text-neutral-500 mb-3">
            Start from a template
          </h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3">
            {templates.map((t, i) => {
              const accents = [
                "var(--c-emerald)",
                "var(--c-sky)",
                "var(--c-amber)",
                "var(--c-violet)",
                "var(--xeno-blue)",
                "var(--c-rose)",
              ];
              const c = accents[i % accents.length];
              return (
                <button
                  key={t.key}
                  onClick={() => onApplyTemplate(t)}
                  className="text-left rounded-lg p-4 transition neu-raised-xs hover:translate-y-[-1px]"
                  style={{
                    background: `linear-gradient(135deg, color-mix(in srgb, ${c}, transparent 92%), color-mix(in srgb, ${c}, transparent 97%))`,
                  }}
                >
                  <div className="text-sm font-medium text-[var(--neu-text)] mb-1">{t.name}</div>
                  <div className="text-xs text-[var(--neu-text-muted)]">{t.description}</div>
                </button>
              );
            })}
          </div>
        </section>

        {/* Builder + Preview side-by-side */}
        <section className="grid lg:grid-cols-5 gap-4">
          {/* Builder */}
          <div className="lg:col-span-3 rounded-lg border border-neutral-800 bg-neutral-900/30 p-5 space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="text-[11px] uppercase tracking-widest text-neutral-500">
                Audience criteria
              </h2>
              {!isPristine && (
                <button
                  onClick={() => {
                    setDefinition(EMPTY_DEFINITION);
                    setName("");
                    setDescription("");
                  }}
                  className="text-[11px] text-neutral-500 hover:text-neutral-300 underline"
                >
                  Reset
                </button>
              )}
            </div>

            <DefinitionEditor definition={definition} onChange={setDefinition} />

            <div className="border-t border-neutral-800 pt-4 space-y-3">
              <h3 className="text-[11px] uppercase tracking-widest text-neutral-500">
                Save segment
              </h3>
              <div className="grid sm:grid-cols-2 gap-2">
                <input
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="Segment name"
                  className="rounded-md border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm placeholder:text-neutral-600 focus:border-emerald-500/50 focus:outline-none"
                />
                <input
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Short description (optional)"
                  className="rounded-md border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm placeholder:text-neutral-600 focus:border-emerald-500/50 focus:outline-none"
                />
              </div>
              {saveError && (
                <div className="text-xs text-red-400">{saveError}</div>
              )}
              <button
                onClick={onSave}
                disabled={saving || !name.trim() || isPristine}
                className="rounded-md border border-emerald-500/40 bg-emerald-500/10 text-emerald-300 px-3 py-1.5 text-sm hover:bg-emerald-500/20 transition disabled:opacity-40"
              >
                {saving ? "Saving…" : "Save segment"}
              </button>
            </div>

            {/* JSON definition (collapsible) */}
            <details className="text-xs">
              <summary className="cursor-pointer text-neutral-500 hover:text-neutral-300">
                Underlying JSON definition
              </summary>
              <pre className="mt-2 rounded border border-neutral-800 bg-neutral-950 px-3 py-2 text-[11px] font-mono text-neutral-300 overflow-x-auto">
                {JSON.stringify(definition, null, 2)}
              </pre>
            </details>
          </div>

          {/* Live preview */}
          <div className="lg:col-span-2">
            <div className="sticky top-4 space-y-3">
              <div className="rounded-lg border border-neutral-800 bg-gradient-to-br from-neutral-900/70 to-neutral-900/10 p-5">
                <div className="text-[10px] uppercase tracking-widest text-neutral-500 mb-1">
                  Live preview
                </div>
                <div className="flex items-baseline gap-2">
                  <div
                    className={`text-4xl font-semibold tabular-nums ${
                      previewing ? "text-neutral-500" : "text-emerald-300"
                    }`}
                  >
                    {preview ? fmtNum(preview.count) : "—"}
                  </div>
                  <div className="text-sm text-neutral-500">customers</div>
                </div>
                {previewing && (
                  <div className="mt-1 text-[11px] text-neutral-500">recalculating…</div>
                )}
              </div>

              {preview && preview.sample.length > 0 && (
                <div className="rounded-lg border border-neutral-800 bg-neutral-900/30 p-4">
                  <div className="text-[10px] uppercase tracking-widest text-neutral-500 mb-2">
                    Sample · why included
                  </div>
                  <div className="space-y-3">
                    {preview.sample.map((s) => (
                      <div key={s.id} className="rounded-md border border-neutral-800 bg-neutral-950/60 p-2.5">
                        <div className="flex items-baseline justify-between mb-1">
                          <Link
                            href={`/customers/${s.id}`}
                            className="text-sm font-medium text-neutral-200 hover:text-emerald-300"
                          >
                            {s.full_name ?? "Unknown"}
                          </Link>
                          <span className="text-[10px] font-mono text-neutral-500">
                            {s.master_customer_id}
                          </span>
                        </div>
                        <div className="text-[11px] text-neutral-500 mb-1.5">
                          {s.city ?? "—"} · {fmtInr(s.lifetime_value)} LTV · {s.total_orders} orders · last {fmtRelative(s.last_order_at)}
                        </div>
                        {s.reasons.length > 0 && (
                          <ul className="space-y-0.5">
                            {s.reasons.map((r, i) => (
                              <li key={i} className="text-[11px] text-emerald-300/90 flex gap-1.5">
                                <span className="text-emerald-500/70">✓</span>
                                <span>{r}</span>
                              </li>
                            ))}
                          </ul>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {preview && preview.count === 0 && (
                <div className="rounded-lg border border-amber-500/30 bg-amber-500/[0.05] p-4 text-xs text-amber-200/80">
                  No customers match these criteria. Loosen a filter or change the consent
                  requirement.
                </div>
              )}
            </div>
          </div>
        </section>

        {/* Saved segments library */}
        <section>
          <div className="flex items-baseline justify-between mb-3">
            <h2 className="text-[11px] uppercase tracking-widest text-neutral-500">
              Saved segments
            </h2>
            <span className="text-xs text-neutral-500">{saved.length} saved</span>
          </div>
          {saved.length === 0 ? (
            <div className="rounded-lg border border-dashed border-neutral-800 bg-neutral-900/30 px-6 py-8 text-center text-sm text-neutral-500">
              No segments saved yet. Build one above and click Save.
            </div>
          ) : (
            <div className="grid md:grid-cols-2 gap-3">
              {saved.map((s) => (
                <SavedSegmentCard key={s.id} segment={s} onDelete={() => onDelete(s.id)} />
              ))}
            </div>
          )}
        </section>
      </div>
    </div>
  );
}

function DefinitionEditor({
  definition,
  onChange,
}: {
  definition: SegmentDefinition;
  onChange: (d: SegmentDefinition) => void;
}) {
  const ac = definition.audience_criteria;
  const sr = definition.suppression_rules;

  const set = (next: Partial<SegmentDefinition>) => onChange({ ...definition, ...next });
  const setAC = (next: Partial<typeof ac>) =>
    set({ audience_criteria: { ...ac, ...next } });
  const setSR = (next: Partial<typeof sr>) =>
    set({ suppression_rules: { ...sr, ...next } });

  return (
    <div className="space-y-4">
      {/* Recency */}
      <FieldGroup label="Recency · last order">
        <div className="flex flex-wrap items-center gap-2">
          <NumInput
            placeholder="≥"
            value={ac.last_order_days_min ?? ""}
            onChange={(v) => setAC({ last_order_days_min: v })}
            suffix="days ago"
          />
          <span className="text-xs text-neutral-600">and / or</span>
          <NumInput
            placeholder="≤"
            value={ac.last_order_days_max ?? ""}
            onChange={(v) => setAC({ last_order_days_max: v })}
            suffix="days ago"
          />
        </div>
      </FieldGroup>

      {/* Value */}
      <FieldGroup label="Value · lifetime value (₹)">
        <div className="flex flex-wrap items-center gap-2">
          <NumInput
            placeholder="≥"
            value={ac.ltv_min ?? ""}
            onChange={(v) => setAC({ ltv_min: v })}
            suffix="INR"
          />
          <span className="text-xs text-neutral-600">to</span>
          <NumInput
            placeholder="≤"
            value={ac.ltv_max ?? ""}
            onChange={(v) => setAC({ ltv_max: v })}
            suffix="INR"
          />
        </div>
      </FieldGroup>

      {/* Frequency */}
      <FieldGroup label="Frequency · total orders">
        <div className="flex flex-wrap items-center gap-2">
          <NumInput
            placeholder="≥"
            value={ac.total_orders_min ?? ""}
            onChange={(v) => setAC({ total_orders_min: v })}
          />
          <span className="text-xs text-neutral-600">to</span>
          <NumInput
            placeholder="≤"
            value={ac.total_orders_max ?? ""}
            onChange={(v) => setAC({ total_orders_max: v })}
          />
        </div>
      </FieldGroup>

      {/* City chips */}
      <FieldGroup label="Cities (any of)">
        <ChipPicker
          options={CITIES}
          selected={ac.cities ?? []}
          onChange={(next) => setAC({ cities: next.length ? next : null })}
        />
      </FieldGroup>

      {/* Loyalty tier chips */}
      <FieldGroup label="Loyalty tier (any of)">
        <ChipPicker
          options={TIERS}
          selected={ac.loyalty_tiers ?? []}
          onChange={(next) => setAC({ loyalty_tiers: next.length ? next : null })}
        />
      </FieldGroup>

      {/* Source coverage */}
      <FieldGroup label="Source coverage · known across">
        <div className="flex items-center gap-1">
          {[null, 1, 2, 3].map((n) => (
            <button
              key={String(n)}
              onClick={() => setAC({ min_source_coverage: n })}
              className={`text-xs rounded-md border px-2.5 py-1 transition ${
                ac.min_source_coverage === n
                  ? "border-emerald-500/50 bg-emerald-500/10 text-emerald-300"
                  : "border-neutral-700 bg-neutral-900 text-neutral-400 hover:bg-neutral-800"
              }`}
            >
              {n === null ? "Any" : `${n}+ sources`}
            </button>
          ))}
        </div>
      </FieldGroup>

      {/* Suppression */}
      <div className="border-t border-neutral-800 pt-4 space-y-3">
        <h3 className="text-[11px] uppercase tracking-widest text-neutral-500">
          Suppression rules
        </h3>
        <div className="flex items-center gap-2">
          <input
            type="checkbox"
            id="exclude-dnd"
            checked={sr.exclude_dnd}
            onChange={(e) => setSR({ exclude_dnd: e.target.checked })}
            className="accent-emerald-500"
          />
          <label htmlFor="exclude-dnd" className="text-sm">
            Exclude TRAI DND-flagged customers
          </label>
        </div>

        <FieldGroup label="Require channel consent">
          <div className="flex flex-wrap items-center gap-1">
            {[
              { v: null, l: "None" },
              { v: "any", l: "Any channel" },
              { v: "whatsapp", l: "WhatsApp" },
              { v: "sms", l: "SMS" },
              { v: "email", l: "Email" },
              { v: "rcs", l: "RCS" },
            ].map((opt) => (
              <button
                key={String(opt.v)}
                onClick={() => setSR({ require_channel_consent: opt.v as never })}
                className={`text-xs rounded-md border px-2.5 py-1 transition ${
                  sr.require_channel_consent === opt.v
                    ? "border-emerald-500/50 bg-emerald-500/10 text-emerald-300"
                    : "border-neutral-700 bg-neutral-900 text-neutral-400 hover:bg-neutral-800"
                }`}
              >
                {opt.l}
              </button>
            ))}
          </div>
        </FieldGroup>
      </div>
    </div>
  );
}

function FieldGroup({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1.5">
        {label}
      </div>
      {children}
    </div>
  );
}

function NumInput({
  placeholder,
  value,
  onChange,
  suffix,
}: {
  placeholder: string;
  value: number | string;
  onChange: (v: number | null) => void;
  suffix?: string;
}) {
  return (
    <div className="inline-flex items-center gap-1.5 rounded-md border border-neutral-700 bg-neutral-950 px-2 py-1">
      <span className="text-neutral-500 text-xs">{placeholder}</span>
      <input
        type="number"
        value={value}
        onChange={(e) => {
          const v = e.target.value;
          onChange(v === "" ? null : Number(v));
        }}
        className="bg-transparent text-sm w-20 focus:outline-none placeholder:text-neutral-700"
      />
      {suffix && <span className="text-neutral-500 text-[11px]">{suffix}</span>}
    </div>
  );
}

function ChipPicker({
  options,
  selected,
  onChange,
}: {
  options: string[];
  selected: string[];
  onChange: (next: string[]) => void;
}) {
  return (
    <div className="flex flex-wrap gap-1">
      {options.map((o) => {
        const on = selected.includes(o);
        return (
          <button
            key={o}
            onClick={() =>
              onChange(on ? selected.filter((s) => s !== o) : [...selected, o])
            }
            className={`text-[11px] rounded-full border px-2 py-0.5 transition ${
              on
                ? "border-emerald-500/50 bg-emerald-500/10 text-emerald-300"
                : "border-neutral-700 bg-neutral-900 text-neutral-400 hover:bg-neutral-800"
            }`}
          >
            {o}
          </button>
        );
      })}
    </div>
  );
}

function SavedSegmentCard({
  segment,
  onDelete,
}: {
  segment: SegmentRow;
  onDelete: () => void;
}) {
  const ac = segment.definition.audience_criteria;
  const sr = segment.definition.suppression_rules;
  const chips: string[] = [];
  if (ac.last_order_days_min != null) chips.push(`Lapsed ≥ ${ac.last_order_days_min}d`);
  if (ac.last_order_days_max != null) chips.push(`Active ≤ ${ac.last_order_days_max}d`);
  if (ac.ltv_min != null) chips.push(`LTV ≥ ₹${ac.ltv_min}`);
  if (ac.total_orders_min != null) chips.push(`Orders ≥ ${ac.total_orders_min}`);
  if (ac.cities && ac.cities.length > 0) chips.push(`${ac.cities.length} cities`);
  if (ac.loyalty_tiers && ac.loyalty_tiers.length > 0) chips.push(`Tiers: ${ac.loyalty_tiers.join(",")}`);
  if (ac.min_source_coverage) chips.push(`${ac.min_source_coverage}+ sources`);
  if (sr.require_channel_consent) {
    const labels: Record<string, React.ReactNode> = {
      whatsapp: <ChannelBadge channel="whatsapp" />,
      sms: <ChannelBadge channel="sms" />,
      email: <ChannelBadge channel="email" />,
      rcs: <ChannelBadge channel="rcs" />,
    };
    if (sr.require_channel_consent !== "any") {
      // handled below as a JSX element
    }
  }

  return (
    <div className="rounded-lg border border-neutral-800 bg-neutral-900/30 p-4">
      <div className="flex items-start justify-between gap-3 mb-1">
        <div className="min-w-0">
          <div className="text-sm font-medium truncate">{segment.name}</div>
          {segment.description && (
            <div className="text-xs text-neutral-500 mt-0.5 line-clamp-2">{segment.description}</div>
          )}
        </div>
        <div className="text-right shrink-0">
          <div className="text-2xl font-semibold text-emerald-300 tabular-nums">
            {fmtNum(segment.preview_count)}
          </div>
          <div className="text-[10px] text-neutral-500">at save time</div>
        </div>
      </div>

      <div className="flex flex-wrap gap-1.5 mt-3">
        {chips.map((c, i) => (
          <span
            key={i}
            className="text-[10px] font-mono rounded bg-neutral-800/80 px-1.5 py-0.5 text-neutral-300"
          >
            {c}
          </span>
        ))}
        {sr.exclude_dnd && (
          <span className="text-[10px] font-mono rounded bg-red-500/15 text-red-300 px-1.5 py-0.5 border border-red-500/30">
            DND excluded
          </span>
        )}
        {sr.require_channel_consent && sr.require_channel_consent !== "any" && (
          <ChannelBadge channel={sr.require_channel_consent} />
        )}
      </div>

      <div className="flex items-center justify-between mt-3 pt-3 border-t border-neutral-800">
        <span className="text-[10px] text-neutral-600 font-mono">#{segment.id}</span>
        <div className="flex items-center gap-2">
          <Link
            href={`/campaigns?segment_id=${segment.id}`}
            className="text-xs text-emerald-400 hover:text-emerald-300"
          >
            Use in campaign →
          </Link>
          <button
            onClick={onDelete}
            className="text-xs text-neutral-500 hover:text-red-400"
          >
            Delete
          </button>
        </div>
      </div>
    </div>
  );
}
